### ISSUE TITLE
Version 7.7 -- Widget World Clock shows incorrect time for few Time Zones

### ISSUE THREAD

**Issue by ruchi1912** [sipcapture/homer-app#219]
How to add  World Clock Widget:
1. Login to GUI
2. Go to '+'  icon to add widget 
3. Select visualize and add "World Clock"

For below time-zones Homer World Clock Widget shows incorrect time
1) Central European Time 
2) Eastern European time
3)  Moscow Standard Time
4) GMT+4
5) GMT+5
6) Japan Standard Time

Screenshot shows the comparison where HEPIC World Clock shows correct time  v/s HOMER World Clock shows incorrect Time

![Central European Time](https://user-images.githubusercontent.com/59015660/71080926-23ff8680-21b4-11ea-859c-4647124de43d.png)
![EET - Eastern European Time](https://user-images.githubusercontent.com/59015660/71080927-24981d00-21b4-11ea-95d4-1c9073ecf7fb.png)
![GMT+4 ](https://user-images.githubusercontent.com/59015660/71080928-24981d00-21b4-11ea-9370-1b4b63d9bbbc.png)
![GMT+5](https://user-images.githubusercontent.com/59015660/71080929-24981d00-21b4-11ea-9f6d-b064e64b0da1.png)
![Japan Standard Time](https://user-images.githubusercontent.com/59015660/71080930-2530b380-21b4-11ea-957f-85762bd1c59e.png)
![Moscow Standard Time](https://user-images.githubusercontent.com/59015660/71080931-2530b380-21b4-11ea-9172-28490aa462cb.png)

**Comment by RFbkak37y3kIY** [comment]
fixed https://gitlab.com/qxip/hepic-ui-3/commit/6432a7263d0f6384ece149245809e61d2efa7922

**Comment by hvspa** [comment]
how this got resolved? my time is also showing incorrect.
date on server cli: Sun Feb 16 03:47:25 +04 2020
date on Homer Home clock:
Asia/Yerevan
19:47:43
Asia/Yerevan

**Comment by adubovikov** [comment]
Resolved in UI: '7.7.026'

**Comment by hvspa** [comment]
thanks much Alexandr,

will it be pushed to docker hub as well?

**Comment by adubovikov** [comment]
yes, should be ;-)

**Comment by hvspa** [comment]
thanks Alexandr, just tried to upgrade the whole thing. removed all containers, images, deleted all volumes and started from scratch.

i see the sipcapture/webapp was updated 7 hours ago, but the time is still showing incorrect...

CLI: Tue Feb 18 05:12:14 +04 2020
GUI: Asia/Yerevan 21:12:15  Asia/Yerevan

the webapp version in docker hub is 021.

docker pull sipcapture/webapp:latest

REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
sipcapture/webapp           latest              0a704502aaba        7 hours ago         32.8MB


do you think you can push 026 to docker hub? thanks

**Comment by hvspa** [comment]
hi Alexandr, can you please help to check if when the 028 pr 026 will be pushed to docker hub and what will be the tag? latest  or what?

**Comment by lmangani** [comment]
the automated builds are pushed to latest

**Comment by hvspa** [comment]
i tried last night and the version was 021:(

**Comment by adubovikov** [comment]
@hvspa please try one more time

**Comment by hvspa** [comment]
> @hvspa please try one more time

заработало :) версия 028 :) спасибо :)

**Comment by hvspa** [comment]
i see there is anew feature there, to export the call flow as a PNG. the PNG does not include the IP address in the top of the call flow tab. can you have a look into that?

thanks again :)

**Comment by adubovikov** [comment]
please open a new ticket for this.

**Comment by hvspa** [comment]
> 
> 
> please open a new ticket for this.

created. thanks much Alexandr,
