### ISSUE TITLE
Web UI: can't add alias

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-app#234]
When I try to add new alias it just throws an error via GUI:
![image](https://user-images.githubusercontent.com/50572561/72538540-44d3fe00-387e-11ea-86fb-38e9176f591f.png)

![image](https://user-images.githubusercontent.com/50572561/72538550-48678500-387e-11ea-886d-ebeeb2a2e06b.png)

Console log from chrome:
[Alias.error.txt](https://github.com/sipcapture/homer-app/files/4072067/Alias.error.txt)

Editing works on existing aliases.

Tested on 1.1.4

Also - if there is an error it should pop up before closing the editing window and erasing all entered information (eg. If I enter invalid mask it should throw an error but not close a window.)

**Comment by adubovikov** [comment]
it has been fixed today, just take the latest webapp from master or wait for a package

**Comment by adubovikov** [comment]
about error, totaly agree - pushing this information to the dev team

**Comment by adubovikov** [comment]
@RFbkak37y3kIY please take it

**Comment by kpribic** [comment]
Tried with latest version, adding still doesn't work, while I can edit existing one.
![image](https://user-images.githubusercontent.com/50572561/72598773-c4aaa880-3910-11ea-8af5-8127583dd93c.png)
![image](https://user-images.githubusercontent.com/50572561/72598780-c8d6c600-3910-11ea-9149-805971e6939a.png)

**Comment by adubovikov** [comment]
we are working on it right now... please wait

**Comment by RFbkak37y3kIY** [comment]
fixed

https://github.com/sipcapture/homer-ui/commit/902b7518de1c096bac36e29d27dccaa699fd352e

https://github.com/sipcapture/homer-ui/commit/d78b6d31292d75af017859c136bb2a4f19a00b33

https://github.com/sipcapture/homer-ui/commit/d09590cf972a29bf3c77600b830e5db581afc6cb
