### ISSUE TITLE
homer-app user permissions

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-app#299]
Command:

```
./homer-app -create-homer-role -database-root-user=postgres -database-host=localhost -database-root-password=postgres -database-homer-data=homer_data -database-homer-config=homer_config
```

will change ownership on the database but will not check ownership/rights on individual tables in that db.

```
# ./homer-app -create-homer-role -database-root-user=postgres -database-host=localhost -database-root-password=***pass*** -database-homer-data=homer_data -database-homer-config=homer_config  
 
CONNECT to DB ROOT STRING: [host=localhost user=postgres dbname=postgres sslmode=disable port=5432 password=***pass***]
 
 
HOMER - creating role for user [user=homer_user dbconfig=homer_config, dbdata=homer_data] 

(/home/shurik/go/src/github.com/sipcapture/homer-app/migration/migration.go:96) 
[2020-02-18 09:02:28]  [3.18ms]  GRANT ALL PRIVILEGES ON DATABASE homer_config to homer_user;  
[0 rows affected or returned ] 

(/home/shurik/go/src/github.com/sipcapture/homer-app/migration/migration.go:99) 
[2020-02-18 09:02:28]  [1.00ms]  GRANT ALL PRIVILEGES ON DATABASE homer_data to homer_user;  
[0 rows affected or returned ] 

(/home/shurik/go/src/github.com/sipcapture/homer-app/migration/migration.go:102) 
[2020-02-18 09:02:28]  [0.19ms]  ALTER DATABASE homer_config OWNER TO homer_user;  
[0 rows affected or returned ] 

(/home/shurik/go/src/github.com/sipcapture/homer-app/migration/migration.go:105) 
[2020-02-18 09:02:28]  [0.19ms]  ALTER DATABASE homer_data OWNER TO homer_user;  
[0 rows affected or returned ] 
 
DONE 
 
HOMER - show users 
        Role name       |       Attributes
------------------------------------------------
        homer_user      |
        postgres        |       superuser, create database
 
DONE 
```

What happened to me was that I manually dropped some tables because of full disk and restarted heplify-server to recreate them. Afterwards homer-app could no longer select data from those tables because homer_user no longer had appropriate rights.

postgres12 log:
```
020-02-18 08:58:08.314 UTC [238920] ERROR:  permission denied for table hep_proto_1_default
```

I had to maunally fix it because homer-app command didn't fix individual tables.
```
GRANT ALL ON TABLE public.hep_proto_1_default TO homer_user;
```
I'm not sure should this be solved on heplify-server side or on homer-app side, but I something should be done somewhere because the automatic recreation of tables doesn't work now and it's a shame because it's a really nice feature.

**Tested on**
homer-app 1.1.29
heplify-server 1.15

**Comment by adubovikov** [comment]
Can you check this one: 

https://github.com/sipcapture/homer-app/blob/master/homer-app

we have fixed it here:
https://github.com/sipcapture/homer-app/commit/8af5675492c295e2630effdac85417e50319b2c7

**Comment by adubovikov** [comment]
btw, for me it also a workaround, because looks like your heplify-server doesn't use homer_user for homer_data. Does it ? If the user is homer_user, all new tables should be created under this role.

**Comment by adubovikov** [comment]
just FYI  homer-app package 1.1.31 has been uploaded

**Comment by kpribic** [comment]
Yes you're correct, at some point I set heplify-server to postgres user and never switched back. I guess this wouldn't have happened otherwise.

I tried the command same with the new binary but I don't think it's working. In postgresql log all I get are:

```
2020-02-18 12:16:29.156 UTC [2224] LOG:  statement: SELECT 'lib/pq ping test';
2020-02-18 12:16:29.156 UTC [2224] LOG:  statement: GRANT ALL PRIVILEGES ON DATABASE homer_config to homer_user;
2020-02-18 12:16:29.158 UTC [2224] LOG:  statement: GRANT ALL PRIVILEGES ON DATABASE homer_data to homer_user;
2020-02-18 12:16:29.159 UTC [2224] LOG:  statement: ALTER DATABASE homer_config OWNER TO homer_user;
2020-02-18 12:16:29.160 UTC [2224] LOG:  statement: ALTER DATABASE homer_data OWNER TO homer_user;
2020-02-18 12:16:29.160 UTC [2224] LOG:  statement:  SELECT  schemaname, tablename, tableowner FROM pg_catalog.pg_tables WHERE schemaname != 'pg_catalog' AND schemaname != 'information_schema' AND tableowner != 'homer_user' AND tablename LIKE 'hep_proto%' AND hasindexes = true
2020-02-18 12:16:29.163 UTC [2224] LOG:  statement:  SELECT u.usename AS "Username", CASE WHEN u.usesuper AND u.usecreatedb THEN CAST('superuser, create database' AS pg_catalog.text)WHEN u.usesuper THEN CAST('superuser' AS pg_catalog.text) WHEN u.usecreatedb THEN CAST('create database' AS  pg_catalog.text)ELSE CAST('' AS pg_catalog.text) END AS "Attributes" FROM pg_catalog.pg_user u ORDER BY 1;

```

There are no obvious alter commands to individual tables I manually deleted and recreated with heplify.
Homer user still doesn't have ownership. In screenshot you can see that tables 1, 35 and 54 are not bold (eg. no permissions)

![image](https://user-images.githubusercontent.com/50572561/74735613-5465ae80-5251-11ea-9ea2-99bd4b1429e9.png)

**Comment by adubovikov** [comment]
Does the query return any records?
```
SELECT  schemaname, tablename, tableowner FROM pg_catalog.pg_tables WHERE schemaname != 'pg_catalog' AND schemaname != 'information_schema' AND tableowner != 'homer_user' AND tablename LIKE 'hep_proto%' AND hasindexes = true
```

**Comment by kpribic** [comment]
Yes, some 400 records:

![image](https://user-images.githubusercontent.com/50572561/74736986-30f03300-5254-11ea-8ef4-6112b03bef3b.png)

**Comment by adubovikov** [comment]
can you try one more time  ?
https://github.com/sipcapture/homer-app/blob/master/homer-app

**Comment by kpribic** [comment]
I deleted and recreated tables 35 and 54.
```
# ./homer-app --version
VERSION: 1.1.32

# /usr/local/bin/homer-app -create-homer-role -database-root-user=postgres -database-host=localhost -database-root-password=***somepassword** -database-homer-data=homer_data -database-homer-config=homer_config
 
CONNECT to DB ROOT STRING: [host=localhost user=postgres dbname=postgres sslmode=disable port=5432 password=***somepassword***]
 
 
HOMER - creating role for user [user=homer_user dbconfig=homer_config, dbdata=homer_data] 

(/home/shurik/go/src/github.com/sipcapture/homer-app/migration/migration.go:96) 
[2020-02-18 14:24:10]  [1.63ms]  GRANT ALL PRIVILEGES ON DATABASE homer_config to homer_user;  
[0 rows affected or returned ] 

(/home/shurik/go/src/github.com/sipcapture/homer-app/migration/migration.go:99) 
[2020-02-18 14:24:10]  [1.15ms]  GRANT ALL PRIVILEGES ON DATABASE homer_data to homer_user;  
[0 rows affected or returned ] 

(/home/shurik/go/src/github.com/sipcapture/homer-app/migration/migration.go:102) 
[2020-02-18 14:24:10]  [0.15ms]  ALTER DATABASE homer_config OWNER TO homer_user;  
[0 rows affected or returned ] 

(/home/shurik/go/src/github.com/sipcapture/homer-app/migration/migration.go:105) 
[2020-02-18 14:24:10]  [0.15ms]  ALTER DATABASE homer_data OWNER TO homer_user;  
[0 rows affected or returned ] 

(/home/shurik/go/src/github.com/sipcapture/homer-app/migration/migration.go:111) 
[2020-02-18 14:24:10]  [3.07ms]   SELECT  schemaname, tablename, tableowner FROM pg_catalog.pg_tables WHERE schemaname != 'pg_catalog' AND schemaname != 'information_schema' AND tableowner != 'homer_user' AND tablename LIKE 'hep_proto%'  
[0 rows affected or returned ] 
 
DONE 
 
HOMER - show users 
        Role name       |       Attributes
------------------------------------------------
        homer_user      |
        postgres        |       superuser, create database
 
DONE 
```
Postgres logs says:
```
2020-02-18 14:30:57.411 UTC [7920] LOG:  statement: GRANT ALL PRIVILEGES ON DATABASE homer_config to homer_user;
2020-02-18 14:30:57.413 UTC [7920] LOG:  statement: GRANT ALL PRIVILEGES ON DATABASE homer_data to homer_user;
2020-02-18 14:30:57.414 UTC [7920] LOG:  statement: ALTER DATABASE homer_config OWNER TO homer_user;
2020-02-18 14:30:57.415 UTC [7920] LOG:  statement: ALTER DATABASE homer_data OWNER TO homer_user;
2020-02-18 14:30:57.415 UTC [7920] LOG:  statement:  SELECT  schemaname, tablename, tableowner FROM pg_catalog.pg_tables WHERE schemaname != 'pg_catalog' AND schemaname != 'information_schema' AND tableowner != 'homer_user' AND tablename LIKE 'hep_proto%'
2020-02-18 14:30:57.423 UTC [7920] LOG:  statement:  SELECT u.usename AS "Username", CASE WHEN u.usesuper AND u.usecreatedb THEN CAST('superuser, create database' AS pg_catalog.text)WHEN u.usesuper THEN CAST('superuser' AS pg_catalog.text) WHEN u.usecreatedb THEN CAST('create database' AS  pg_catalog.text)ELSE CAST('' AS pg_catalog.text) END AS "Attributes" FROM pg_catalog.pg_user u ORDER BY 1;

```
I don't know why this isn't returning rows according to heplify-app output.
When I use the same query (copy/paste from log above) directly to db first query gets 407 rows as a result, and the second one only two (postgres and homer_user).

**Comment by kpribic** [comment]
Forgot to mention - didn't change the individual table permissions, as you can see from queries.

**Comment by adubovikov** [comment]
and one more time, please
https://github.com/sipcapture/homer-app/blob/master/homer-app

**Comment by kpribic** [comment]
Works! :-)

**Comment by adubovikov** [comment]
super. The issue is - you have to be connected to "homer_data" DB, otherwise it doesn't show the tables.
